<span style='color:blue ; font-size:30px ; font-weght:bold ; font-family:"Arial "  '>
    Import Libraries
</span>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

<span style='color:blue ; font-size:30px ; font-weght:bold ; font-family:"Arial "  '>
    Importing & Reading The Data
</span>

In [2]:
df = pd.read_csv('consumer_complaints.csv')
pd.set_option('display.max_columns',None)
df.head(7)

,date_received,product,sub_product,issue,sub_issue,consumer_complaint_narrative,company_public_response,company,state,zipcode,tags,consumer_consent_provided,submitted_via,date_sent_to_company,company_response_to_consumer,timely_response,consumer_disputed?,complaint_id
0,08/30/2013,Mortgage,Other mortgage,"Loan modification,collection,foreclosure",NaN,NaN,NaN,U.S. Bancorp,CA,95993,NaN,NaN,Referral,09/03/2013,Closed with explanation,Yes,Yes,511074
1,08/30/2013,Mortgage,Other mortgage,"Loan servicing, payments, escrow account",NaN,NaN,NaN,Wells Fargo & Company,CA,91104,NaN,NaN,Referral,09/03/2013,Closed with explanation,Yes,Yes,511080
2,08/30/2013,Credit reporting,NaN,Incorrect information on credit report,Account status,NaN,NaN,Wells Fargo & Company,NY,11764,NaN,NaN,Postal mail,09/18/2013,Closed with explanation,Yes,No,510473
3,08/30/2013,Student loan,Non-federal student loan,Repaying your loan,Repaying your loan,NaN,NaN,"Navient Solutions, Inc.",MD,21402,NaN,NaN,Email,08/30/2013,Closed with explanation,Yes,Yes,510326
4,08/30/2013,Debt collection,Credit card,False statements or representation,Attempted to collect wrong amount,NaN,NaN,Resurgent Capital Services L.P.,GA,30106,NaN,NaN,Web,08/30/2013,Closed with explanation,Yes,Yes,511067
5,08/30/2013,Credit card,NaN,Application processing delay,NaN,NaN,NaN,Capital One,NY,12206,NaN,NaN,Phone,09/03/2013,Closed with explanation,Yes,Yes,510098
6,08/30/2013,Credit card,NaN,Credit line increase/decrease,NaN,NaN,NaN,Wells Fargo & Company,AZ,85730,NaN,NaN,Postal mail,09/05/2013,Closed with explanation,Yes,No,511062

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 555957 entries, 0 to 555956
Data columns (total 18 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   date_received                 555957 non-null  object
 1   product                       555957 non-null  object
 2   sub_product                   397635 non-null  object
 3   issue                         555957 non-null  object
 4   sub_issue                     212622 non-null  object
 5   consumer_complaint_narrative  66806 non-null   object
 6   company_public_response       85124 non-null   object
 7   company                       555957 non-null  object
 8   state                         551070 non-null  object
 9   zipcode                       551452 non-null  object
 10  tags                          77959 non-null   object
 11  consumer_consent_provided     123458 non-null  object
 12  submitted_via                 555957 non-null  object
 13  date_sent_to_company          555957 non-null  object
 14  company_response_to_consumer  555957 non-null  object
 15  timely_response               555957 non-null  object
 16  consumer_disputed?            555957 non-null  object
 17  complaint_id                  555957 non-null  int64
dtypes: int64(1), object(17)
memory usage: 76.3+ MB

In [4]:
df['date_received'] = pd.to_datetime(df['date_received'])
df['date_sent_to_company'] = pd.to_datetime(df['date_sent_to_company'])

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 555957 entries, 0 to 555956
Data columns (total 18 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   date_received                 555957 non-null  datetime64[ns]
 1   product                       555957 non-null  object
 2   sub_product                   397635 non-null  object
 3   issue                         555957 non-null  object
 4   sub_issue                     212622 non-null  object
 5   consumer_complaint_narrative  66806 non-null   object
 6   company_public_response       85124 non-null   object
 7   company                       555957 non-null  object
 8   state                         551070 non-null  object
 9   zipcode                       551452 non-null  object
 10  tags                          77959 non-null   object
 11  consumer_consent_provided     123458 non-null  object
 12  submitted_via                 555957 non-null  object
 13  date_sent_to_company          555957 non-null  datetime64[ns]
 14  company_response_to_consumer  555957 non-null  object
 15  timely_response               555957 non-null  object
 16  consumer_disputed?            555957 non-null  object
 17  complaint_id                  555957 non-null  int64
dtypes: datetime64[ns](2), int64(1), object(15)
memory usage: 76.3+ MB

In [6]:
df.isna().sum()

date_received                        0
product                              0
sub_product                     158322
issue                                0
sub_issue                       343335
consumer_complaint_narrative    489151
company_public_response         470833
company                              0
state                             4887
zipcode                           4505
tags                            477998
consumer_consent_provided       432499
submitted_via                        0
date_sent_to_company                 0
company_response_to_consumer         0
timely_response                      0
consumer_disputed?                   0
complaint_id                         0
dtype: int64

In [7]:
df.drop(columns=[
    'sub_product',
    'sub_issue',
    'consumer_complaint_narrative',
    'company_public_response',
    'zipcode',
    'tags',
    'consumer_consent_provided'
], inplace=True)

In [8]:
df.isna().sum()

date_received                      0
product                            0
issue                              0
company                            0
state                           4887
submitted_via                      0
date_sent_to_company               0
company_response_to_consumer       0
timely_response                    0
consumer_disputed?                 0
complaint_id                       0
dtype: int64

In [9]:
df.dropna(subset=['state'] , inplace=True)

In [10]:
df.isna().sum()

date_received                   0
product                         0
issue                           0
company                         0
state                           0
submitted_via                   0
date_sent_to_company            0
company_response_to_consumer    0
timely_response                 0
consumer_disputed?              0
complaint_id                    0
dtype: int64

In [11]:
df.duplicated().sum()

0

In [12]:
check_list = ['product','issue','company'
              ,'state','submitted_via','company_response_to_consumer'
              ,'timely_response','consumer_disputed?']

def unique_value_check(df,col_name):
    '''Unique values check'''
    x = df[col_name].value_counts(dropna= False)
    print(x)

for col_name in check_list :
    print(col_name)
    unique_value_check(df,col_name)
    print('\n')

product
product
Mortgage                   185187
Debt collection            100348
Credit reporting            91244
Credit card                 65875
Bank account or service     61352
Consumer Loan               20838
Student loan                15722
Payday loan                  3846
Money transfers              3673
Prepaid card                 2443
Other financial service       542
Name: count, dtype: int64


issue
issue
Loan modification,collection,foreclosure    96433
Incorrect information on credit report      66330
Loan servicing, payments, escrow account    60017
Cont'd attempts collect debt not owed       42003
Account opening, closing, or management     26046
                                            ...
Lost or stolen money order                     24
Incorrect exchange rate                        13
Lender sold the property                        5
Lender damaged or destroyed vehicle             4
Lender damaged or destroyed property            1
Name: count, Length: 95, dtype: int64


company
company
Bank of America               55402
Wells Fargo & Company         41547
JPMorgan Chase & Co.          33506
Equifax                       31610
Experian                      30720
                              ...
Kirkland Financial LLC            1
Segan, Mason & Mason, P.C.        1
M & S FUNDING, INC.               1
99th Floor LLC                    1
Pohler and Associates, LLC        1
Name: count, Length: 3599, dtype: int64


state
state
CA    81700
FL    53673
TX    41352
NY    38266
GA    24548
      ...
MH       27
MP       19
AS       17
PW        9
AA        9
Name: count, Length: 62, dtype: int64


submitted_via
submitted_via
Web            359872
Referral       107772
Phone           38986
Postal mail     36276
Fax              7869
Email             295
Name: count, dtype: int64


company_response_to_consumer
company_response_to_consumer
Closed with explanation            400709
Closed with non-monetary relief     69692
Closed with monetary relief         37855
Closed without relief               17816
Closed                              13242
Closed with relief                   5263
In progress                          3729
Untimely response                    2764
Name: count, dtype: int64


timely_response
timely_response
Yes    537131
No      13939
Name: count, dtype: int64


consumer_disputed?
consumer_disputed?
No     439789
Yes    111281
Name: count, dtype: int64

In [13]:
df['response_status'] = df['company_response_to_consumer'].map({
    'Closed with monetary relief': 'Resolved',
    'Closed with non-monetary relief': 'Resolved',
    'Closed with relief': 'Resolved',
    'Closed with explanation': 'Unresolved',
    'Closed without relief': 'Unresolved',
    'Closed': 'Unresolved',
    'Untimely response': 'Unresolved',
    'In progress': 'In Progress'
})

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 551070 entries, 0 to 553096
Data columns (total 12 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   date_received                 551070 non-null  datetime64[ns]
 1   product                       551070 non-null  object
 2   issue                         551070 non-null  object
 3   company                       551070 non-null  object
 4   state                         551070 non-null  object
 5   submitted_via                 551070 non-null  object
 6   date_sent_to_company          551070 non-null  datetime64[ns]
 7   company_response_to_consumer  551070 non-null  object
 8   timely_response               551070 non-null  object
 9   consumer_disputed?            551070 non-null  object
 10  complaint_id                  551070 non-null  int64
 11  response_status               551070 non-null  object
dtypes: datetime64[ns](2), int64(1), object(9)
memory usage: 54.7+ MB

In [15]:
df = df[
    [
        'complaint_id',
        'date_received',
        'date_sent_to_company',
        'product',
        'issue',
        'company',
        'state',
        'submitted_via',
        'company_response_to_consumer',
        'response_status',
        'timely_response',
        'consumer_disputed?'
    ]
]
df.head()

,complaint_id,date_received,date_sent_to_company,product,issue,company,state,submitted_via,company_response_to_consumer,response_status,timely_response,consumer_disputed?
0,511074,2013-08-30,2013-09-03,Mortgage,"Loan modification,collection,foreclosure",U.S. Bancorp,CA,Referral,Closed with explanation,Unresolved,Yes,Yes
1,511080,2013-08-30,2013-09-03,Mortgage,"Loan servicing, payments, escrow account",Wells Fargo & Company,CA,Referral,Closed with explanation,Unresolved,Yes,Yes
2,510473,2013-08-30,2013-09-18,Credit reporting,Incorrect information on credit report,Wells Fargo & Company,NY,Postal mail,Closed with explanation,Unresolved,Yes,No
3,510326,2013-08-30,2013-08-30,Student loan,Repaying your loan,"Navient Solutions, Inc.",MD,Email,Closed with explanation,Unresolved,Yes,Yes
4,511067,2013-08-30,2013-08-30,Debt collection,False statements or representation,Resurgent Capital Services L.P.,GA,Web,Closed with explanation,Unresolved,Yes,Yes

In [17]:
#df.to_csv('Consumer_Complaints_Clean.csv',index=False)